---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1l0c3w8qs6ll8kntkxvj5wa0qfyu3zhljtcqyezpmawgfn3hy2c4q8jxh70"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1l0c3w8qs6ll8kntkxvj5wa0qfyu3zhljtcqyezpmawgfn3hy2c4q8jxh70"
stores:
  yaml:
    indent: 2
