# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:w0x+u9GVfi4SRNig05UnCs7IK66ojnED8AgUVxSv8DI=,iv:lE3lS17i8MPkNlt1ZKpLug4Rmaw0gH7pHpXbpKs7Cpk=,tag:IRrWfIDUzjCjfGPAC1xzmg==,type:str]
sops:
  age:
    - recipient: age1l0c3w8qs6ll8kntkxvj5wa0qfyu3zhljtcqyezpmawgfn3hy2c4q8jxh70
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOXdFRjBZYU5wOE9ka1p6
        Sko5MmZpa2h2Z0FQUzVkVUh0Y2x4cnpzNkFvCnJJWk1Ia0dOcHhhd1NUMzEweXRx
        akFxQ2lXRXJJYmRPQ1VWNFh1ZSt5WGMKLS0tIDFRM1IwK2hxeWV3STJvbWNYcFFD
        WG0rVU5lN0lhYlEvUEp3S2pFOUJ0VTgKMCcjCGGHdPevEWNquFZOsBL/BTm1iWIo
        JqMZM8BfkbGhZfeWgFGvNbysm6XAh0aXcc0+5vdFg0qa5/FmFFbWrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T20:02:22Z"
  mac: ENC[AES256_GCM,data:x6flAguIu7AUHA9Odi/yCzj+D+nWlamdnWr3j4ApD/fAevoD2wFw1Ki+bvADX0QpsxFS9bRoVY6xc27KuCQbN+V3D+xzfxU6ude/9DTnwhJSsOTfEafUnvqvz+6XBqs0gDfRbKrxgRp3QtduRtNeZ6Bja3w+zgIYnjzTQgrCbjI=,iv:GX8d0g5pFaJhFowMUZhgPq/3xxRopnhdV2RNe46Rm3Y=,tag:FTB6yZWJRKZPyIoRoGYWBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
